'use strict';
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),distance=(a,b,c,d)=>Math.hypot(a-c,b-d);
const S={scene:'alley',x:22,y:83,tx:22,ty:83,path:[],hp:100,items:[],docs:{},flags:{},dialog:[],inDialog:false,selectedItem:null,selectedDoc:null,playing:false,finished:false,lastHit:0,saveKey:'tenebris-w-v3'};
const ui={title:$('title'),help:$('help'),game:$('game'),bg:$('background'),walker:$('walker'),sparks:$('sparkles'),tap:$('tapMark'),loc:$('location'),obj:$('objective'),hint:$('hint'),health:$('healthFill'),healthText:$('healthText'),dialog:$('dialog'),speaker:$('speaker'),dialogText:$('dialogText'),inv:$('inventory'),items:$('items'),itemDesc:$('itemDesc'),docs:$('documents'),docList:$('docList'),docText:$('docText'),ending:$('ending'),endingText:$('endingText')};

const SCENES={
 alley:{name:'SOUTH HARBOR — CARMONA',bg:'assets/alley.webp',spawn:[22,84],nodes:{a:[22,84],b:[40,82],c:[58,81],d:[72,79]},edges:{a:['b'],b:['a','c'],c:['b','d'],d:['c']},objective(){if(!S.flags.alleyReport)return 'Inspecter la scène de Carmona.';if(!S.flags.room3)return 'Rejoindre l’accès de Morrow, chambre 3.';return 'Entrer dans Morrow.'},hotspots:[
  {id:'report',x:31,y:82,dest:[31,84],kind:'item',once:true,act(){S.flags.alleyReport=1;addDoc('Rapport Carmona','Périmètre levé trop vite. Le corps a quitté la chaîne de procédure. Un agent local note une liaison probable avec Morrow, chambre 3.');return [['WALKER','Le rapport a été nettoyé, mais pas assez. Morrow, chambre 3.']] }},
  {id:'ammo',x:67,y:79,dest:[64,82],kind:'item',once:true,act(){addItem('Munitions UFST','Deux chargeurs de service.');return [['WALKER','Deux chargeurs. Je prends.']] }},
  {id:'morrowDoor',x:60.5,y:55.5,dest:[58,78],kind:'door',act(){S.flags.room3=1;return [['WALKER','Chambre 3. La trajectoire continue ici.'],['GO','motel']]}}
 ]},
 motel:{name:'MORROW — CHAMBRE 3',bg:'assets/motel.webp',spawn:[79,83],nodes:{a:[79,83],b:[66,82],c:[53,83],d:[39,84],e:[24,84],f:[71,75]},edges:{a:['b','f'],b:['a','c','f'],c:['b','d'],d:['c','e'],e:['d'],f:['a','b']},objective(){if(!S.flags.motelTape)return 'Fouiller la chambre 3.';if(!S.flags.serviceKey)return 'Trouver l’accès au réseau de maintenance.';return 'Utiliser la clé de maintenance.'},hotspots:[
  {id:'tape',x:25,y:70,dest:[29,83],kind:'item',once:true,act(){S.flags.motelTape=1;addDoc('Transcription 03:12','Voix féminine: « Il sait déjà. Walker remontera la trajectoire. Faites-le passer par Morrow. »');return [['DOCUMENT','La bande cite ton nom avant même l’ouverture officielle de l’enquête.']] }},
  {id:'spray',x:16,y:62,dest:[24,83],kind:'item',once:true,act(){addItem('Spray hémostatique','Restaure une partie de la santé de Walker.');return [['WALKER','Ça peut me garder debout.']] }},
  {id:'serviceKey',x:79,y:68,dest:[72,78],kind:'item',once:true,act(){S.flags.serviceKey=1;addItem('Clé maintenance','Clé SOUTH HARBOR — SERVICE.');return [['WALKER','Voilà mon accès.']] }},
  {id:'serviceDoor',x:72,y:40,dest:[71,74],kind:'door',act(){if(!S.flags.serviceKey)return [['WALKER','Verrouillée. Il me faut une clé.']];return [['GO','tunnel']] }},
  {id:'back',x:91,y:59,dest:[80,80],kind:'door',act(){return [['GO','alley']]}}
 ]},
 tunnel:{name:'RÉSEAU TECHNIQUE — SOUTH HARBOR',bg:'assets/tunnel.webp',spawn:[73,84],nodes:{a:[73,84],b:[61,82],c:[50,81],d:[40,79],e:[31,77]},edges:{a:['b'],b:['a','c'],c:['b','d'],d:['c','e'],e:['d']},objective(){if(!S.flags.fuse)return 'Rétablir l’alimentation de l’annexe Voss.';return 'Atteindre l’annexe Voss Biomedical.'},hotspots:[
  {id:'vossDoc',x:57,y:74,dest:[57,81],kind:'item',once:true,act(){addDoc('Bordereau Voss','CV-P9 / annexe isolée / alimentation secondaire / exposition indirecte du sujet W.');return [['WALKER','Sujet W… ça commence à devenir personnel.']] }},
  {id:'fuse',x:79,y:58,dest:[69,79],kind:'item',once:true,act(){S.flags.fuse=1;addItem('Fusible industriel','Fusible de secours pour réseau Voss.');return [['WALKER','Le courant revient avec ça.']] }},
  {id:'vossDoor',x:82,y:43,dest:[72,76],kind:'door',act(){if(!S.flags.fuse)return [['WALKER','Porte morte. Le circuit secondaire est coupé.']];return [['GO','lab']] }},
  {id:'back',x:25,y:66,dest:[31,78],kind:'door',act(){return [['GO','motel']]}}
 ]},
 lab:{name:'VOSS BIOMEDICAL — ANNEXE CV-P9',bg:'assets/lab.webp',spawn:[47,86],nodes:{a:[47,86],b:[38,80],c:[50,76],d:[62,77],e:[69,83]},edges:{a:['b','c','e'],b:['a','c'],c:['a','b','d'],d:['c','e'],e:['a','d']},objective(){if(!S.flags.profile)return 'Identifier pourquoi Voss suit Walker.';if(!S.flags.purge)return 'Déclencher la purge de l’annexe CV-P9.';return 'FUIR — rejoindre la sortie avant verrouillage.'},hotspots:[
  {id:'profile',x:51,y:49,dest:[50,75],kind:'item',once:true,act(){S.flags.profile=1;addDoc('PROFIL W','WALKER, ETHAN — réponse active confirmée à CARMONA / MORROW / C-4 / REDMOND. Maintenir exposition indirecte. Valeur adaptative : élevée.');return [['DOCUMENT','Ils ne documentent pas tes découvertes. Ils documentent tes réactions.']] }},
  {id:'console',x:52,y:49,dest:[54,74],kind:'console',act(){if(!S.flags.profile)return [['WALKER','Je veux d’abord savoir ce qu’ils faisaient ici.']];if(!S.flags.purge){S.flags.purge=1;return [['SYSTÈME','PURGE CV-P9 ARMÉE. VERROUILLAGE EN COURS.'],['WALKER','Très bien. Maintenant je sors.']]};return [['SYSTÈME','PURGE EN COURS.']] }},
  {id:'exit',x:77,y:38,dest:[69,76],kind:'door',act(){if(!S.flags.purge)return [['WALKER','Je ne pars pas sans fermer ce site.']];finish();return []}},
  {id:'back',x:31,y:38,dest:[38,77],kind:'door',act(){return [['GO','tunnel']]}}
 ]}
};

function scene(){return SCENES[S.scene]}
function addItem(name,desc){S.items.push({name,desc})}
function addDoc(name,text){S.docs[name]=text}
function save(){if(!S.playing||S.finished)return;try{localStorage.setItem(S.saveKey,JSON.stringify({scene:S.scene,x:S.x,y:S.y,hp:S.hp,items:S.items,docs:S.docs,flags:S.flags}))}catch(e){}}
function load(){try{const d=JSON.parse(localStorage.getItem(S.saveKey));if(!d)return false;Object.assign(S,{scene:d.scene||'alley',x:d.x??22,y:d.y??84,tx:d.x??22,ty:d.y??84,hp:d.hp??100,items:d.items||[],docs:d.docs||{},flags:d.flags||{}});return true}catch(e){return false}}
function reset(){Object.assign(S,{scene:'alley',x:22,y:84,tx:22,ty:84,path:[],hp:100,items:[],docs:{},flags:{},dialog:[],inDialog:false,selectedItem:null,selectedDoc:null,playing:false,finished:false,lastHit:0})}
function showScreen(el){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('visible'));if(el)el.classList.add('visible')}
function start(cont=false){if(!cont||!load()){reset();const sp=SCENES.alley.spawn;S.x=S.tx=sp[0];S.y=S.ty=sp[1];queue([['MERCER','Walker. Ortega reste au QG. Tu suis Carmona jusqu’à Morrow et tu coupes court au premier signal anormal.'],['WALKER','Reçu.'],['SYSTÈME','Les éléments importants du décor produisent un bref scintillement blanc.']])}ui.title.classList.remove('visible');ui.help.classList.remove('visible');ui.ending.classList.remove('visible');ui.game.classList.remove('hidden');S.playing=true;refreshScene();save()}
function refreshScene(){ui.bg.src=scene().bg;ui.loc.textContent=scene().name;const sp=scene().spawn;if(!Number.isFinite(S.x)){S.x=S.tx=sp[0];S.y=S.ty=sp[1]}renderWalker();renderSparkles();updateHud()}
function updateHud(){ui.obj.textContent=scene().objective();const hp=clamp(S.hp,0,100);ui.health.style.width=hp+'%';ui.health.style.background=hp>60?'#7f9b80':hp>30?'#b79a64':'#a94b4b';ui.healthText.textContent=hp>60?'STABLE':hp>30?'BLESSÉ':'DANGER'}
function renderWalker(){ui.walker.style.left=S.x+'%';ui.walker.style.top=S.y+'%';const scale=.58+clamp((S.y-58)/36,0,1)*.48;ui.walker.style.transform=`translate(-50%,-93%) scale(${scale})`}
function renderSparkles(){ui.sparks.innerHTML='';for(const h of scene().hotspots){if(h.once&&S.flags['used_'+h.id])continue;const d=document.createElement('div');d.className='spark';d.style.left=h.x+'%';d.style.top=h.y+'%';d.dataset.id=h.id;d.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();moveToHotspot(h)});d.addEventListener('touchend',e=>{e.preventDefault();e.stopPropagation();moveToHotspot(h)},{passive:false});ui.sparks.appendChild(d)}}
function queue(lines){if(!lines||!lines.length)return;S.dialog.push(...lines);if(!S.inDialog)nextDialog()}
function nextDialog(){const n=S.dialog.shift();if(!n){S.inDialog=false;ui.dialog.classList.add('hidden');return}if(n[0]==='GO'){changeScene(n[1]);nextDialog();return}S.inDialog=true;ui.speaker.textContent=n[0];ui.dialogText.textContent=n[1];ui.dialog.classList.remove('hidden')}
function changeScene(name){S.scene=name;const sp=scene().spawn;S.x=S.tx=sp[0];S.y=S.ty=sp[1];S.path=[];refreshScene();save()}
function graphRoute(from,to){const sc=scene(),nodes=sc.nodes,keys=Object.keys(nodes);const nearest=p=>keys.reduce((best,k)=>distance(...nodes[k],...p)<distance(...nodes[best],...p)?k:best,keys[0]);const start=nearest(from),goal=nearest(to);const q=[start],prev={[start]:null};while(q.length){const k=q.shift();if(k===goal)break;for(const n of sc.edges[k]||[])if(!(n in prev)){prev[n]=k;q.push(n)}}const route=[];let cur=goal;while(cur){route.unshift(nodes[cur]);cur=prev[cur]}route.push(to);return route}
function moveToHotspot(h){const route=graphRoute([S.x,S.y],h.dest);S.path=route.slice(1).map(p=>[p[0],p[1],null]);if(S.path.length)S.path[S.path.length-1][2]=()=>trigger(h)}
function trigger(h){if(h.once&&S.flags['used_'+h.id])return;const out=h.act();if(h.once)S.flags['used_'+h.id]=1;renderSparkles();updateHud();save();if(out&&out.length)queue(out)}
function tapScene(e){if(!S.playing||S.inDialog)return;const r=$('scene').getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;ui.tap.style.left=x+'%';ui.tap.style.top=y+'%';ui.tap.classList.remove('show');void ui.tap.offsetWidth;ui.tap.classList.add('show');const route=graphRoute([S.x,S.y],[x,clamp(y,68,88)]);S.path=route.slice(1).map(p=>[p[0],p[1],null])}
function damage(n){const now=performance.now();if(now-S.lastHit<1400)return;S.lastHit=now;S.hp=clamp(S.hp-n,0,100);updateHud();if(S.hp===0){S.hp=45;const sp=scene().spawn;S.x=S.tx=sp[0];S.y=S.ty=sp[1];S.path=[];queue([['RAPPORT UFST','Walker reprend connaissance. Il a perdu du temps, pas la piste.']])}}
function renderItems(){ui.items.innerHTML='';if(!S.items.length)ui.items.innerHTML='<div class="item">VIDE</div>';S.items.forEach((it,i)=>{const b=document.createElement('button');b.className='item'+(S.selectedItem===i?' sel':'');b.textContent=it.name;b.onclick=()=>{S.selectedItem=i;ui.itemDesc.textContent=it.desc;renderItems()};ui.items.appendChild(b)})}
function useItem(){const i=S.selectedItem;if(i==null||!S.items[i])return;const it=S.items[i];if(it.name==='Spray hémostatique'){S.hp=clamp(S.hp+45,0,100);S.items.splice(i,1);S.selectedItem=null;ui.itemDesc.textContent='Walker utilise le spray.';renderItems();updateHud();save()}else ui.itemDesc.textContent=it.desc}
function renderDocs(){ui.docList.innerHTML='';const arr=Object.entries(S.docs);if(!arr.length){ui.docList.innerHTML='<div class="doc">AUCUN DOCUMENT</div>';ui.docText.textContent='Aucun document.';return}arr.forEach(([k,v])=>{const b=document.createElement('button');b.className='doc'+(S.selectedDoc===k?' sel':'');b.textContent=k;b.onclick=()=>{S.selectedDoc=k;ui.docText.textContent=v;renderDocs()};ui.docList.appendChild(b)})}
function finish(){S.finished=true;S.playing=false;ui.game.classList.add('hidden');ui.endingText.textContent='Walker déclenche la purge de l’annexe CV-P9 et quitte South Harbor avec la certitude que sa trajectoire était observée avant même qu’il comprenne l’existence du dispositif.';ui.ending.classList.add('visible');try{localStorage.removeItem(S.saveKey)}catch(e){}}
let last=performance.now();function loop(now){const dt=Math.min(32,now-last)/1000;last=now;if(S.playing&&!S.inDialog){if(S.path.length){const t=S.path[0],dx=t[0]-S.x,dy=t[1]-S.y,d=Math.hypot(dx,dy);if(d<.5){S.x=t[0];S.y=t[1];const cb=t[2];S.path.shift();if(!S.path.length){ui.walker.classList.remove('walking');if(cb)cb()}}else{ui.walker.classList.add('walking');const sp=23;S.x+=dx/d*sp*dt;S.y+=dy/d*sp*dt;renderWalker()}}else ui.walker.classList.remove('walking');document.querySelectorAll('.spark').forEach(el=>{const h=scene().hotspots.find(x=>x.id===el.dataset.id);if(h)el.classList.toggle('near',distance(S.x,S.y,...h.dest)<10)})}requestAnimationFrame(loop)}requestAnimationFrame(loop);
$('newBtn').onclick=()=>start(false);$('continueBtn').onclick=()=>start(true);$('helpBtn').onclick=()=>showScreen(ui.help);$('backBtn').onclick=()=>showScreen(ui.title);$('againBtn').onclick=()=>{reset();showScreen(ui.title);$('continueBtn').disabled=true};$('invBtn').onclick=()=>{renderItems();ui.inv.classList.remove('hidden')};$('closeInvBtn').onclick=()=>ui.inv.classList.add('hidden');$('useBtn').onclick=useItem;$('docsBtn').onclick=()=>{renderDocs();ui.docs.classList.remove('hidden')};$('closeDocsBtn').onclick=()=>ui.docs.classList.add('hidden');ui.dialog.onclick=nextDialog;$('scene').addEventListener('click',tapScene);window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save()});$('continueBtn').disabled=!load();reset();showScreen(ui.title);
