'use strict';
const $=id=>document.getElementById(id);
const UI={title:$('title'),help:$('help'),game:$('game'),bg:$('bg'),walker:$('walker'),enemy:$('enemy'),tap:$('tap'),hud:$('hud'),actions:$('actions'),loc:$('location'),obj:$('objective'),hp:$('hpbar'),hptext:$('hptext'),dialog:$('dialog'),speaker:$('speaker'),text:$('dialogText'),inv:$('inventory'),slots:$('slots'),desc:$('desc'),docs:$('docs'),docList:$('docList'),docText:$('docText'),ending:$('ending'),endText:$('endText')};
const SAVE='tenebris-walker-v2'; let G=null,last=performance.now(),queue=[],selected=-1,selectedDoc=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), d=(a,b,c,e)=>Math.hypot(a-c,b-e);
const SC={
 alley:{name:'CARMONA STREET — SOUTH HARBOR',bg:'assets/alley_ps1.jpg',spawn:[20,82],walk:[10,82,67,91],obj:g=>g.f.morrow?'Entrer dans Morrow — chambre 3.':'Inspecter Carmona et trouver la suite de la scène.',hot:[
  {id:'report',x:24,y:82,r:7,to:[24,82],once:1,go:g=>{g.docs['Rapport Carmona']='07:48 — corps non identifié, périmètre nettoyé trop tôt. Une piste relie la scène à Morrow, chambre 3.';return[['WALKER','Ils ont nettoyé avant même qu’on sache quoi chercher.'],['DOCUMENT','Une mention : MORROW — CHAMBRE 3.']] }},
  {id:'ammo',x:74,y:82,r:6,to:[70,84],once:1,go:g=>{g.inv.push({n:'Munitions UFST',t:'Deux chargeurs de réserve.'});return[['WALKER','Je prends.']] }},
  {id:'morrow',x:62,y:70,r:7,to:[58,82],go:g=>{g.f.morrow=1;return[['WALKER','Chambre 3.'],['GO','motel']]}}
 ]},
 motel:{name:'MORROW — CHAMBRE 3',bg:'assets/motel_ps1.jpg',spawn:[18,84],walk:[12,88,67,91],obj:g=>g.f.key?'Ouvrir la porte de maintenance.':'Fouiller la chambre 3.',hot:[
  {id:'backM',x:14,y:78,r:7,to:[18,84],go:g=>[['GO','alley']]},
  {id:'spray',x:30,y:76,r:6,to:[30,84],once:1,go:g=>{g.inv.push({n:'Spray hémostatique',t:'Restaure 45 points de santé.'});return[['WALKER','Kit de terrain.']] }},
  {id:'tape',x:23,y:70,r:7,to:[28,84],once:1,go:g=>{g.docs['Transcription 03:12']='Voix féminine : « Walker remontera la trajectoire. Faites-le passer par Morrow. »';return[['DOCUMENT','La bande prononce ton nom avant le début officiel de l’enquête.']] }},
  {id:'key',x:76,y:77,r:7,to:[70,84],once:1,go:g=>{g.f.key=1;g.inv.push({n:'Clé maintenance',t:'SOUTH HARBOR — SERVICE.'});return[['WALKER','Ça ouvre quelque chose derrière Morrow.']] }},
  {id:'service',x:73,y:62,r:8,to:[68,82],go:g=>g.f.key?[['GO','tunnel']]:[['WALKER','Verrouillée. Il me faut une clé.']]}
 ]},
 tunnel:{name:'RÉSEAU TECHNIQUE — SOUTH HARBOR',bg:'assets/tunnel_ps1.jpg',spawn:[18,84],walk:[16,82,70,91],obj:g=>g.f.fuse?'Rejoindre l’annexe Voss.':'Rétablir l’alimentation de l’accès Voss.',enemy:1,hot:[
  {id:'backT',x:18,y:78,r:7,to:[19,84],go:g=>[['GO','motel']]},
  {id:'vossdoc',x:56,y:80,r:6,to:[56,84],once:1,go:g=>{g.docs['Bordereau Voss']='CV-P9 / ANNEXE ISOLÉE / autorisation locale / fusible industriel de secours.';return[['WALKER','Voss Biomedical. Voilà le nom qu’ils cachaient.']] }},
  {id:'fuse',x:68,y:73,r:7,to:[65,84],once:1,go:g=>{g.f.fuse=1;g.inv.push({n:'Fusible industriel',t:'Compatible avec le tableau Voss.'});return[['WALKER','De quoi réveiller leur accès.']] }},
  {id:'voss',x:79,y:74,r:7,to:[74,84],go:g=>g.f.fuse?[['GO','lab']]:[['WALKER','Aucune alimentation. Il manque un fusible.']]}
 ]},
 lab:{name:'VOSS BIOMEDICAL — CV-P9',bg:'assets/lab_ps1.jpg',spawn:[25,84],walk:[16,83,68,91],obj:g=>g.f.purge?'FUITE — rejoindre la sortie de service.':'Lire le terminal puis déclencher la purge.',enemy:1,hot:[
  {id:'backL',x:20,y:78,r:7,to:[24,84],go:g=>[['GO','tunnel']]},
  {id:'profile',x:52,y:72,r:7,to:[50,84],once:1,go:g=>{g.docs['PROFIL W']='WALKER, ETHAN — réponse active confirmée à CARMONA / MORROW / C-4 / REDMOND. Maintenir exposition indirecte. Valeur adaptative : élevée.';g.f.profile=1;return[['DOCUMENT','PROFIL W — TRAJECTOIRE MAINTENUE.'],['WALKER','Je ne suivais pas leur piste. C’est leur piste qui me suivait.']] }},
  {id:'console',x:55,y:75,r:7,to:[53,84],go:g=>{if(!g.f.profile)return[['SYSTÈME','AUTHENTIFICATION REFUSÉE — PROFIL NON CHARGÉ.']];if(!g.f.purge){g.f.purge=1;return[['SYSTÈME','PURGE CV-P9. VERROUILLAGE D’URGENCE.'],['WALKER','Maintenant on sort.']] }return[['SYSTÈME','PURGE EN COURS.']] }},
  {id:'exit',x:73,y:74,r:8,to:[69,84],go:g=>{if(!g.f.purge)return[['WALKER','Pas avant d’avoir détruit ce qu’ils ont ici.']];finish();return[]}}
 ]}
};
function fresh(){return{scene:'alley',x:20,y:82,tx:20,ty:82,hp:100,inv:[],docs:{},f:{},used:{},pending:null,enemyX:58,enemyY:84,enemyDir:1,playing:1}}
function save(){if(!G||!G.playing)return;try{localStorage.setItem(SAVE,JSON.stringify(G))}catch(e){}}
function load(){try{let x=JSON.parse(localStorage.getItem(SAVE));if(x&&SC[x.scene]){G=x;return 1}}catch(e){}return 0}
function screen(on){UI.title.classList.toggle('hidden',on);UI.game.classList.toggle('hidden',!on);UI.hud.classList.toggle('hidden',!on);UI.actions.classList.toggle('hidden',!on)}
function start(cont){if(!cont||!load())G=fresh();screen(1);UI.help.classList.add('hidden');UI.ending.classList.add('hidden');scene();if(!cont) say([['MERCER','Walker. Ortega reste au QG. Carmona, Morrow, puis tu ressors. Pas de raccourci.'],['WALKER','Reçu.']] )}
function scene(){let s=SC[G.scene];UI.bg.src=s.bg;UI.loc.textContent=s.name;UI.obj.textContent=s.obj(G);let sp=s.spawn;if(!Number.isFinite(G.x)){G.x=sp[0];G.y=sp[1]}G.tx=G.x;G.ty=G.y;G.pending=null;G.enemyX=G.scene==='lab'?33:58;G.enemyY=84;G.enemyDir=1;UI.enemy.classList.toggle('hidden',!s.enemy);render();save()}
function render(){let scale=.55+(G.y-66)/42;UI.walker.style.left=G.x+'%';UI.walker.style.top=G.y+'%';UI.walker.style.transform=`translate(-50%,-100%) scale(${scale})`;if(SC[G.scene].enemy){UI.enemy.style.left=G.enemyX+'%';UI.enemy.style.top=G.enemyY+'%';UI.enemy.style.transform=`translate(-50%,-100%) scale(${.55+(G.enemyY-66)/42})`}UI.hp.style.width=G.hp+'%';UI.hp.style.background=G.hp>60?'#829786':G.hp>30?'#aa8b55':'#983d3d';UI.hptext.textContent=G.hp>60?'STABLE':G.hp>30?'BLESSÉ':'DANGER';UI.obj.textContent=SC[G.scene].obj(G)}
function say(arr){if(arr&&arr.length)queue.push(...arr);if(!UI.dialog.dataset.open)nextSay()}
function nextSay(){let q=queue.shift();if(!q){delete UI.dialog.dataset.open;UI.dialog.classList.add('hidden');return}if(q[0]==='GO'){change(q[1]);return nextSay()}UI.dialog.dataset.open='1';UI.speaker.textContent=q[0];UI.text.textContent=q[1];UI.dialog.classList.remove('hidden')}
function change(n){G.scene=n;let p=SC[n].spawn;G.x=p[0];G.y=p[1];G.tx=G.x;G.ty=G.y;scene()}
function tapPos(e){let r=UI.game.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100}}
function hotspot(p){let best=null,bd=99;for(let h of SC[G.scene].hot){if(h.once&&G.used[h.id])continue;let z=d(p.x,p.y,h.x,h.y);if(z<=h.r&&z<bd){best=h;bd=z}}return best}
function sceneTap(e){if(!G||UI.dialog.dataset.open||!UI.inv.classList.contains('hidden')||!UI.docs.classList.contains('hidden'))return;e.preventDefault();let p=tapPos(e);UI.tap.style.left=p.x+'%';UI.tap.style.top=p.y+'%';UI.tap.classList.remove('pop');void UI.tap.offsetWidth;UI.tap.classList.add('pop');let h=hotspot(p),w=SC[G.scene].walk;if(h){G.tx=h.to[0];G.ty=h.to[1];G.pending=h}else{G.tx=clamp(p.x,w[0],w[1]);G.ty=clamp(p.y,w[2],w[3]);G.pending=null}}
function runHot(h){if(h.once)G.used[h.id]=1;let out=h.go(G)||[];render();save();say(out)}
function hit(n){if(G.hurt&&performance.now()-G.hurt<900)return;G.hurt=performance.now();G.hp=clamp(G.hp-n,0,100);if(navigator.vibrate)navigator.vibrate(45);if(G.hp<=0){G.hp=45;let p=SC[G.scene].spawn;G.x=p[0];G.y=p[1];G.tx=G.x;G.ty=G.y;say([['WALKER','Pas maintenant...']])}render();save()}
function inv(){selected=-1;UI.slots.innerHTML='';if(!G.inv.length)UI.slots.innerHTML='<div class="slot">VIDE</div>';G.inv.forEach((o,i)=>{let b=document.createElement('button');b.className='slot';b.textContent=o.n;b.onclick=()=>{selected=i;[...UI.slots.children].forEach(x=>x.classList.remove('sel'));b.classList.add('sel');UI.desc.textContent=o.t};UI.slots.appendChild(b)});UI.inv.classList.remove('hidden')}
function use(){if(selected<0||!G.inv[selected])return;let o=G.inv[selected];if(o.n==='Spray hémostatique'){G.hp=clamp(G.hp+45,0,100);G.inv.splice(selected,1);selected=-1;UI.desc.textContent='Walker utilise le spray.';render();save();inv()}else UI.desc.textContent=o.t}
function docs(){UI.docList.innerHTML='';UI.docText.textContent='Sélectionne un document.';let a=Object.entries(G.docs);if(!a.length)UI.docList.innerHTML='<div class="doc">AUCUN DOCUMENT</div>';a.forEach(([k,v])=>{let b=document.createElement('button');b.className='doc';b.textContent=k;b.onclick=()=>{[...UI.docList.children].forEach(x=>x.classList.remove('sel'));b.classList.add('sel');UI.docText.textContent=v};UI.docList.appendChild(b)});UI.docs.classList.remove('hidden')}
function finish(){G.playing=0;screen(0);UI.title.classList.add('hidden');UI.ending.classList.remove('hidden');UI.endText.textContent='Walker quitte l’annexe CV-P9 avant le verrouillage. Son rapport officiel ne mentionnera jamais le Collecteur 9. Mais le dossier PROFIL W prouve une chose : Carmona, Morrow et South Harbor n’étaient pas une suite de coïncidences. C’était une trajectoire.';try{localStorage.removeItem(SAVE)}catch(e){}}
function loop(t){let dt=Math.min(.035,(t-last)/1000);last=t;if(G&&G.playing&&!UI.dialog.dataset.open&&UI.inv.classList.contains('hidden')&&UI.docs.classList.contains('hidden')){let dx=G.tx-G.x,dy=G.ty-G.y,z=Math.hypot(dx,dy);if(z>.3){let v=24;G.x+=dx/z*v*dt;G.y+=dy/z*v*dt}else if(G.pending){let h=G.pending;G.pending=null;runHot(h)}if(SC[G.scene].enemy){G.enemyX+=G.enemyDir*(G.scene==='lab'?4.2:5.4)*dt;let lo=G.scene==='lab'?31:45,hi=G.scene==='lab'?68:72;if(G.enemyX<lo||G.enemyX>hi)G.enemyDir*=-1;if(d(G.x,G.y,G.enemyX,G.enemyY)<5.2){hit(G.scene==='lab'?18:10);G.tx=G.x=clamp(G.x-5,SC[G.scene].walk[0],SC[G.scene].walk[1])}}render()}requestAnimationFrame(loop)}
$('newBtn').onclick=()=>start(0);$('continueBtn').onclick=()=>start(1);$('helpBtn').onclick=()=>{UI.title.classList.add('hidden');UI.help.classList.remove('hidden')};$('backBtn').onclick=()=>{UI.help.classList.add('hidden');UI.title.classList.remove('hidden')};$('invBtn').onclick=inv;$('docsBtn').onclick=docs;$('closeInv').onclick=()=>UI.inv.classList.add('hidden');$('closeDocs').onclick=()=>UI.docs.classList.add('hidden');$('useBtn').onclick=use;$('dialog').onclick=nextSay;$('againBtn').onclick=()=>{UI.ending.classList.add('hidden');UI.title.classList.remove('hidden')};UI.game.addEventListener('pointerup',sceneTap);window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save()});try{$('continueBtn').disabled=!localStorage.getItem(SAVE)}catch(e){}requestAnimationFrame(loop);