'use strict';
const $=id=>document.getElementById(id), C=$('game'), X=C.getContext('2d');
const UI={title:$('title'),help:$('help'),hud:$('hud'),controls:$('controls'),dialog:$('dialog'),speaker:$('speaker'),dialogText:$('dialogText'),inv:$('inventory'),slots:$('slots'),desc:$('desc'),ending:$('ending'),hp:$('hpbar'),hptext:$('hptext'),ammo:$('ammo'),loc:$('location'),obj:$('objective')};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), dist=(a,b,c,d)=>Math.hypot(a-c,b-d), norm=a=>Math.atan2(Math.sin(a),Math.cos(a));
let G=null,last=0,joy={x:0,y:0},aim=false,run=false,paused=false,selected=null,dialogQueue=[],audio=null;
const SAVE='tenebris-walker-mobile-v3';
function storageGet(){try{return localStorage.getItem(SAVE)}catch(e){return null}} function storageSet(v){try{localStorage.setItem(SAVE,v)}catch(e){}} function storageDel(){try{localStorage.removeItem(SAVE)}catch(e){}}
function tone(f=90,d=.08){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;o.type='triangle';g.gain.value=.025;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.stop(audio.currentTime+d)}catch(e){}}
const rooms={
 alley:{name:'CARMONA STREET — 08:19',w:100,h:70,cam:0,doors:[{x:92,z:35,to:'morrow',tx:8,tz:45,label:'ACCÈS MORROW'}],objects:[{id:'a1',x:18,z:15,type:'ammo',name:'Munitions UFST'},{id:'a2',x:54,z:49,type:'note',name:'Note de Henderson'},{id:'a3',x:78,z:18,type:'key',name:'Clé chambre 3',flag:'morrowKey'}]},
 morrow:{name:'MORROW — CHAMBRE 3',w:100,h:70,cam:1,doors:[{x:7,z:45,to:'alley',tx:88,tz:35,label:'RUE'},{x:93,z:18,to:'tunnel',tx:9,tz:54,label:'PORTE TECHNIQUE',need:'serviceKey'}],objects:[{id:'m1',x:44,z:20,type:'note',name:'Transcription appel 03:12'},{id:'m2',x:68,z:50,type:'med',name:'Spray hémostatique'},{id:'m3',x:79,z:25,type:'key',name:'Clé maintenance',flag:'serviceKey',need:'morrowKey'}]},
 tunnel:{name:'RÉSEAU TECHNIQUE — SOUTH HARBOR',w:120,h:68,cam:2,doors:[{x:8,z:54,to:'morrow',tx:88,tz:18,label:'MORROW'},{x:112,z:34,to:'voss',tx:10,tz:35,label:'ANNEXE VOSS',need:'fuse'}],objects:[{id:'t1',x:34,z:17,type:'ammo',name:'Chargeur 9 mm'},{id:'t2',x:62,z:48,type:'note',name:'Bordereau Voss Biomedical'},{id:'t3',x:92,z:20,type:'fuse',name:'Fusible industriel',flag:'fuse'}]},
 voss:{name:'VOSS BIOMEDICAL — ANNEXE',w:110,h:75,cam:3,doors:[{x:9,z:35,to:'tunnel',tx:106,tz:34,label:'TUNNEL'},{x:101,z:58,to:'collector',tx:12,tz:55,label:'CV-P9 / ACCÈS PRIMAIRE',need:'p9'}],objects:[{id:'v1',x:27,z:54,type:'save',name:'Terminal UFST'},{id:'v2',x:49,z:20,type:'note',name:'Dossier PROFIL W'},{id:'v3',x:82,z:36,type:'terminal',name:'Terminal Voss',flag:'p9'}]},
 collector:{name:'COLLECTEUR 9 — ACCÈS PRIMAIRE',w:120,h:78,cam:4,doors:[{x:10,z:55,to:'voss',tx:96,tz:58,label:'ANNEXE VOSS'},{x:112,z:18,to:'exit',tx:0,tz:0,label:'SORTIE DE SERVICE',need:'purged'}],objects:[{id:'c1',x:35,z:20,type:'ammo',name:'Munitions de réserve'},{id:'c2',x:66,z:57,type:'panel',name:'Commande de purge',flag:'purged'},{id:'c3',x:93,z:45,type:'note',name:'Journal expérimental H-01'}]}
};
function fresh(){return {room:'alley',x:12,z:38,a:0,hp:100,ammo:12,reserve:24,inv:[],notes:[],flags:{},taken:{},kills:0,shots:0,hits:0,start:Date.now(),objective:'Inspecter la scène de Carmona et trouver un accès à Morrow.'}}
function enemies(){return {
 alley:[{id:'e1',type:'host',x:65,z:38,hp:3}],morrow:[{id:'e2',type:'host',x:54,z:42,hp:3}],tunnel:[{id:'e3',type:'frag',x:70,z:35,hp:2},{id:'e4',type:'host',x:103,z:52,hp:3}],voss:[{id:'e5',type:'frag',x:58,z:48,hp:2}],collector:[{id:'h01',type:'h01',x:83,z:22,hp:999}]
}[G.room]||[]}
let E={}; function roomEnemies(){if(!E[G.room])E[G.room]=enemies();return E[G.room]}
function save(){if(!G)return;storageSet(JSON.stringify({G,E}))} function load(){try{let v=JSON.parse(storageGet());if(v&&v.G){G=v.G;E=v.E||{};return true}}catch(e){}return false}
function say(s,t,next){dialogQueue.push({s,t,next});if(dialogQueue.length===1)showDialog()}
function showDialog(){let d=dialogQueue[0];if(!d){UI.dialog.classList.add('hidden');paused=false;return}paused=true;UI.speaker.textContent=d.s;UI.dialogText.textContent=d.t;UI.dialog.classList.remove('hidden')}
function nextDialog(){let d=dialogQueue.shift();if(d&&d.next)d.next();showDialog()}
function start(newGame){if(newGame){G=fresh();E={};storageDel()}else if(!load()){G=fresh();E={}}UI.title.classList.add('hidden');UI.help.classList.add('hidden');UI.hud.classList.remove('hidden');UI.controls.classList.remove('hidden');UI.ending.classList.add('hidden');paused=false;last=performance.now();if(newGame){say('MERCER','Walker. Ortega est retenue au QG. Tu vérifies Carmona, tu photographies, et tu ressors. Pas de raccourci.');say('WALKER','Reçu. Une scène, dix minutes.');}requestAnimationFrame(loop)}
function objective(){if(!G.flags.morrowKey)return 'Trouver ce qui relie Carmona à la chambre 3 de Morrow.';if(!G.flags.serviceKey)return 'Inspecter la chambre 3 et ouvrir l’accès technique.';if(!G.flags.fuse)return 'Suivre les conduits et rétablir l’alimentation de l’annexe Voss.';if(!G.flags.p9)return 'Accéder au terminal Voss.';if(!G.flags.purged)return 'Collecteur 9 : déclencher la purge. H-01 ne doit pas sortir.';return 'FUITE — rejoindre la sortie de service.'}
function tap(el,fn){let lastTap=0;const go=e=>{if(e){e.preventDefault();e.stopPropagation()}let n=Date.now();if(n-lastTap<250)return;lastTap=n;fn(e)};el.addEventListener('click',go);el.addEventListener('touchend',go,{passive:false})}
function useObject(o){if(G.taken[o.id]&&o.type!=='save'&&o.type!=='panel'&&o.type!=='terminal')return;if(o.need&&!G.flags[o.need]){say('WALKER','Il me manque quelque chose pour ouvrir ça.');return}
 if(o.type==='ammo'){G.reserve+=12;G.taken[o.id]=1;say('WALKER','Deux chargeurs. Ça ne fera pas de miracles.');tone(160)}
 else if(o.type==='med'){G.inv.push('Spray hémostatique');G.taken[o.id]=1;say('WALKER','Kit de terrain. Je le garde.');}
 else if(['key','fuse'].includes(o.type)){G.inv.push(o.name);G.flags[o.flag]=1;G.taken[o.id]=1;say('WALKER',o.name+' récupéré.');}
 else if(o.type==='note'){if(!G.notes.includes(o.name))G.notes.push(o.name);G.taken[o.id]=1;let text=o.id==='v2'?'WALKER, ETHAN — réponse active confirmée. Maintenir exposition indirecte. TRAJECTOIRE W.':o.id==='c3'?'CHASSEUR H-01 — orientation aux stimuli de traque. Adaptation aux sujets résistants.':'Un document relie cette zone aux collectes sanitaires non déclarées.';say('DOCUMENT',text);}
 else if(o.type==='save'){save();say('TERMINAL UFST','Progression sauvegardée. Aucun réseau extérieur disponible.');}
 else if(o.type==='terminal'){G.flags.p9=1;say('TERMINAL VOSS','CV-P9 / ACCÈS PRIMAIRE — autorisation locale accordée.');say('WALKER','Ils avaient mon nom avant l’enquête…');tone(62,.3)}
 else if(o.type==='panel'){if(!G.flags.p9){say('SYSTÈME','ACCÈS REFUSÉ.');return}G.flags.purged=1;let h=roomEnemies().find(e=>e.id==='h01');if(h){h.stun=999;h.x=77;h.z=30}say('SYSTÈME','PURGE D’URGENCE. 90 SECONDES AVANT VERROUILLAGE.');say('WALKER','Cours.');tone(55,.45)}save()}
function interact(){if(paused||!G)return;let best=null,bd=11;for(let d of rooms[G.room].doors){let q=dist(G.x,G.z,d.x,d.z);if(q<bd){best={door:d};bd=q}}for(let o of rooms[G.room].objects){if(G.taken[o.id]&&o.type!=='save'&&o.type!=='panel'&&o.type!=='terminal')continue;let q=dist(G.x,G.z,o.x,o.z);if(q<bd){best={obj:o};bd=q}}if(!best){if(aim)shoot();else say('WALKER','Rien d’utile ici.');return}if(best.obj)return useObject(best.obj);let d=best.door;if(d.need&&!G.flags[d.need]){say('WALKER','Verrouillé.');return}if(d.to==='exit'){finish();return}door(d)}
function door(d){paused=true;UI.controls.classList.add('hidden');X.fillStyle='#000';X.fillRect(0,0,480,270);X.strokeStyle='#565e56';X.strokeRect(216,70,48,125);X.fillStyle='#8b918b';X.fillRect(252,132,3,3);setTimeout(()=>{G.room=d.to;G.x=d.tx;G.z=d.tz;G.a=0;paused=false;UI.controls.classList.remove('hidden');save();if(G.room==='collector'&&!G.flags.seenH){G.flags.seenH=1;say('RADIO','…Walker… trajectoire maintenue…');say('WALKER','Qui est sur cette fréquence ?');}},420)}
function reload(){if(G.ammo>=12||G.reserve<=0)return;let n=Math.min(12-G.ammo,G.reserve);G.ammo+=n;G.reserve-=n;tone(130,.12)}
function shoot(){if(paused||!aim)return;if(G.ammo<=0){reload();if(G.ammo<=0)tone(45,.05);return}G.ammo--;G.shots++;tone(90,.07);let hit=null,score=.34;for(let e of roomEnemies()){if(e.dead||e.stun>0)continue;let a=Math.atan2(e.z-G.z,e.x-G.x),da=Math.abs(norm(a-G.a)),d=dist(G.x,G.z,e.x,e.z);let s=da+d/350;if(da<.42&&d<55&&s<score){hit=e;score=s}}if(hit){G.hits++;if(hit.type==='h01'){hit.stun=.22;say('WALKER','Ça ne l’arrête pas.');}else{hit.hp--;hit.stun=.3;if(hit.hp<=0){hit.dead=1;G.kills++}}}if(G.ammo===0)reload()}
function hurt(n){if(G.hurt>0)return;G.hp=clamp(G.hp-n,0,100);G.hurt=.8;tone(48,.18);if(G.hp<=0){G.hp=30;say('RAPPORT UFST','Walker perd connaissance. Dernière sauvegarde restaurée.',()=>{if(!load()){G=fresh();E={}}})}}
function update(dt){if(paused||!G)return;G.hurt=Math.max(0,(G.hurt||0)-dt);let turn=joy.x,forward=-joy.y;if(Math.abs(turn)<.08)turn=0;if(Math.abs(forward)<.08)forward=0;G.a+=turn*dt*2.3;let sp=(run?25:15)*forward;G.x+=Math.cos(G.a)*sp*dt;G.z+=Math.sin(G.a)*sp*dt;let r=rooms[G.room];G.x=clamp(G.x,5,r.w-5);G.z=clamp(G.z,5,r.h-5);for(let e of roomEnemies()){if(e.dead)continue;e.stun=Math.max(0,(e.stun||0)-dt);if(e.stun>0)continue;let d=dist(G.x,G.z,e.x,e.z);if(d<(e.type==='h01'?65:38)){let a=Math.atan2(G.z-e.z,G.x-e.x),s=e.type==='h01'?11:e.type==='frag'?8:6;e.x+=Math.cos(a)*s*dt;e.z+=Math.sin(a)*s*dt;if(d<5)hurt(e.type==='h01'?28:12)}}G.objective=objective()}
function proj(x,z){let r=rooms[G.room],cam=r.cam,px,pz;if(cam===0){px=x/r.w; pz=z/r.h}else if(cam===1){px=1-x/r.w;pz=z/r.h}else if(cam===2){px=z/r.h;pz=1-x/r.w}else if(cam===3){px=1-z/r.h;pz=1-x/r.w}else{px=x/r.w;pz=1-z/r.h}let y=55+pz*175,scale=.55+pz*.72;return{x:35+px*410,y,scale}}
function bg(){let r=rooms[G.room];X.fillStyle=['#101310','#11100f','#0d1110','#101413','#090b0a'][r.cam];X.fillRect(0,0,480,270);let g=X.createLinearGradient(0,45,0,260);g.addColorStop(0,'#20251f');g.addColorStop(1,'#050706');X.fillStyle=g;X.beginPath();X.moveTo(20,55);X.lineTo(460,55);X.lineTo(520,270);X.lineTo(-40,270);X.fill();X.strokeStyle='rgba(140,150,140,.13)';for(let i=0;i<9;i++){X.beginPath();X.moveTo(240,55);X.lineTo(-50+i*75,270);X.stroke()}for(let y=75;y<270;y+=28){X.beginPath();X.moveTo(0,y);X.lineTo(480,y);X.stroke()}X.fillStyle='rgba(0,0,0,.4)';X.fillRect(0,0,480,48);X.fillRect(0,250,480,20)}
function drawThing(o){let p=proj(o.x,o.z);X.save();X.translate(p.x,p.y);let near=dist(G.x,G.z,o.x,o.z)<11,s=p.scale;if(o.type==='ammo'){X.fillStyle='#806f42';X.fillRect(-6*s,-6*s,12*s,6*s)}else if(o.type==='med'){X.fillStyle='#d4d7cf';X.fillRect(-6*s,-7*s,12*s,7*s);X.fillStyle='#7e2525';X.fillRect(-1*s,-7*s,2*s,6*s)}else if(['key','fuse'].includes(o.type)){X.fillStyle='#9b9362';X.fillRect(-5*s,-3*s,10*s,3*s)}else if(o.type==='note'){X.fillStyle='#b8b49b';X.fillRect(-6*s,-8*s,12*s,8*s)}else{X.fillStyle='#313a33';X.fillRect(-7*s,-16*s,14*s,16*s);X.fillStyle=o.type==='panel'?'#9c2929':'#79a17f';X.fillRect(-3*s,-12*s,6*s,3*s)}if(near){X.strokeStyle='#d4d9d3';X.beginPath();X.arc(0,-8*s,10,0,Math.PI*2);X.stroke()}X.restore()}
function drawDoor(d){let p=proj(d.x,d.z),s=p.scale;X.fillStyle=d.need&&!G.flags[d.need]?'#281617':'#242a25';X.fillRect(p.x-8*s,p.y-27*s,16*s,27*s);X.strokeStyle='#647065';X.strokeRect(p.x-8*s,p.y-27*s,16*s,27*s)}
function drawEnemy(e){let p=proj(e.x,e.z),s=p.scale*(e.type==='h01'?1.45:e.type==='frag'?.8:1);X.save();X.translate(p.x,p.y);X.fillStyle=e.type==='h01'?'#0b0808':e.type==='frag'?'#111':'#252825';if(e.type==='frag'){X.beginPath();X.moveTo(-7*s,0);X.lineTo(-3*s,-15*s);X.lineTo(2*s,-8*s);X.lineTo(7*s,0);X.fill()}else{X.fillRect(-4*s,-20*s,8*s,20*s);X.beginPath();X.arc(0,-24*s,5*s,0,Math.PI*2);X.fill();X.fillRect(-8*s,-16*s,4*s,15*s);X.fillRect(4*s,-16*s,4*s,15*s);if(e.type==='h01'){X.fillStyle='#7b1d1d';X.fillRect(-1*s,-26*s,2*s,2*s)}}X.restore()}
function drawPlayer(){let p=proj(G.x,G.z),s=p.scale;X.save();X.translate(p.x,p.y);X.fillStyle='#17201b';X.fillRect(-4*s,-19*s,8*s,19*s);X.fillStyle='#3d5548';X.fillRect(-5*s,-18*s,10*s,7*s);X.fillStyle='#baa58f';X.beginPath();X.arc(0,-23*s,4.5*s,0,Math.PI*2);X.fill();X.strokeStyle=aim?'#d9ddd6':'#263229';X.lineWidth=2;X.beginPath();X.moveTo(0,-13*s);X.lineTo(Math.cos(G.a)*11*s,-13*s+Math.sin(G.a)*6*s);X.stroke();X.restore()}
function render(){bg();for(let d of rooms[G.room].doors)drawDoor(d);for(let o of rooms[G.room].objects)if(!G.taken[o.id]||['save','panel','terminal'].includes(o.type))drawThing(o);let arr=roomEnemies().filter(e=>!e.dead).map(e=>({z:e.z,fn:()=>drawEnemy(e)}));arr.push({z:G.z,fn:drawPlayer});arr.sort((a,b)=>a.z-b.z).forEach(x=>x.fn());UI.hp.style.width=G.hp+'%';UI.hp.style.background=G.hp<35?'#8c2525':'#7f9782';UI.hptext.textContent=G.hp>70?'STABLE':G.hp>35?'BLESSÉ':'CRITIQUE';UI.ammo.textContent=String(G.ammo).padStart(2,'0')+' / '+String(G.reserve).padStart(2,'0');UI.loc.textContent=rooms[G.room].name;UI.obj.textContent=G.objective}
function loop(t){if(!G)return;let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);render();requestAnimationFrame(loop)}
function openInv(){if(!G||paused)return;paused=true;UI.controls.classList.add('hidden');UI.inv.classList.remove('hidden');selected=null;renderInv()}function closeInv(){UI.inv.classList.add('hidden');UI.controls.classList.remove('hidden');paused=false}
function renderInv(){UI.slots.innerHTML='';let a=G.inv.map(x=>({n:x,t:'OBJET'})).concat(G.notes.map(x=>({n:x,t:'DOCUMENT'})));while(a.length<8)a.push(null);a.slice(0,12).forEach(it=>{let d=document.createElement('div');d.className='slot';if(it){d.innerHTML='<b>'+it.t+'</b>'+it.n;tap(d,()=>{selected=it.n;[...UI.slots.children].forEach(x=>x.classList.remove('sel'));d.classList.add('sel');UI.desc.textContent=it.n==='Spray hémostatique'?'Restaure 45% de l’état de Walker.':'Élément conservé dans le dossier de Walker.'})}else d.innerHTML='<span style="opacity:.25">VIDE</span>';UI.slots.appendChild(d)})}
function useSelected(){if(selected==='Spray hémostatique'){if(G.hp>=100){UI.desc.textContent='État déjà stable.';return}G.hp=clamp(G.hp+45,0,100);G.inv.splice(G.inv.indexOf(selected),1);selected=null;renderInv();UI.desc.textContent='Traitement appliqué.';save()}else if(selected)UI.desc.textContent='Cet objet est utilisé automatiquement quand il est nécessaire.'}
function finish(){let sec=Math.max(1,(Date.now()-G.start)/1000),acc=G.shots?G.hits/G.shots:1,score=1000-sec+G.hp*3+acc*250+G.kills*30,rank=score>1120?'S':score>900?'A':score>680?'B':'C';UI.hud.classList.add('hidden');UI.controls.classList.add('hidden');UI.ending.classList.remove('hidden');$('rank').textContent=rank;$('stats').innerHTML='TEMPS — '+Math.floor(sec/60)+'m '+Math.floor(sec%60)+'s<br>ÉTAT — '+G.hp+'%<br>PRÉCISION — '+Math.round(acc*100)+'%<br>NEUTRALISÉS — '+G.kills+'<br><br>Le rapport officiel de Walker ne mentionnera jamais le Collecteur 9.';storageDel();G=null}
let stick=$('stick'),knob=$('knob'),activePointer=null;function stickMove(x,y){let r=stick.getBoundingClientRect(),dx=x-(r.left+r.width/2),dy=y-(r.top+r.height/2),m=Math.hypot(dx,dy),mx=42;if(m>mx){dx=dx/m*mx;dy=dy/m*mx}joy.x=dx/mx;joy.y=dy/mx;knob.style.transform='translate('+dx+'px,'+dy+'px)'}function stickEnd(){joy.x=joy.y=0;knob.style.transform=''}
stick.addEventListener('pointerdown',e=>{activePointer=e.pointerId;try{stick.setPointerCapture(e.pointerId)}catch(_){}stickMove(e.clientX,e.clientY)});stick.addEventListener('pointermove',e=>{if(e.pointerId===activePointer)stickMove(e.clientX,e.clientY)});stick.addEventListener('pointerup',stickEnd);stick.addEventListener('pointercancel',stickEnd);stick.addEventListener('touchstart',e=>{e.preventDefault();let t=e.touches[0];if(t)stickMove(t.clientX,t.clientY)},{passive:false});stick.addEventListener('touchmove',e=>{e.preventDefault();let t=e.touches[0];if(t)stickMove(t.clientX,t.clientY)},{passive:false});stick.addEventListener('touchend',e=>{e.preventDefault();stickEnd()},{passive:false});
function hold(el,set){el.addEventListener('pointerdown',e=>{e.preventDefault();set(true);el.classList.add('on')});['pointerup','pointercancel','pointerleave'].forEach(n=>el.addEventListener(n,()=>{set(false);el.classList.remove('on')}));el.addEventListener('touchstart',e=>{e.preventDefault();set(true);el.classList.add('on')},{passive:false});el.addEventListener('touchend',e=>{e.preventDefault();set(false);el.classList.remove('on')},{passive:false})}
hold($('aimBtn'),v=>aim=v);hold($('runBtn'),v=>run=v);tap($('actBtn'),()=>aim?shoot():interact());tap($('invBtn'),openInv);tap(UI.dialog,nextDialog);tap($('closeInv'),closeInv);tap($('useBtn'),useSelected);tap($('newBtn'),()=>start(true));tap($('continueBtn'),()=>start(false));tap($('helpBtn'),()=>{UI.title.classList.add('hidden');UI.help.classList.remove('hidden')});tap($('backBtn'),()=>{UI.help.classList.add('hidden');UI.title.classList.remove('hidden')});tap($('againBtn'),()=>start(true));
$('continueBtn').disabled=!storageGet();window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save()});
function titleBg(){if(G)return;X.fillStyle='#050605';X.fillRect(0,0,480,270);X.fillStyle='#131713';for(let i=0;i<8;i++)X.fillRect(35+i*58,60+(i%3)*10,24,155-(i%4)*17);X.strokeStyle='#391b1b';X.beginPath();X.moveTo(0,220);X.bezierCurveTo(130,150,340,245,480,180);X.stroke();requestAnimationFrame(titleBg)}titleBg();
